in:
  type: file
  path_prefix: /root/opt/csv/sample
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: col1, type: long}
    - {name: col2, type: long}
out: {type: stdout}
